# Generated by Django 2.2 on 2019-07-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=100)),
                ('sgender', models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=6)),
                ('srow', models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR')], max_length=5)),
            ],
        ),
    ]
