# Generated by Django 2.2 on 2019-07-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20190723_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sgender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female'), ('N', 'None')], default='Select', max_length=6),
        ),
        migrations.AlterField(
            model_name='student',
            name='srow',
            field=models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO'), (3, 'THREE'), (4, 'FOUR')], default='Select'),
        ),
    ]
